# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "Setup PowerShell Toolkit"
author: "hugoalh Studio"
description: "Setup PowerShell module `hugoalh.GitHubActionsToolkit`."
inputs:
  sudo:
    description: "{Boolean} Whether to execute this action in sudo mode on non-Windows environment."
    required: false
    default: "False"
  version:
    description: "{String} Target version."
    required: false
    default: "Latest"
  allowprerelease:
    description: "{Boolean} Whether to allow target pre release version."
    required: false
    default: "False"
  scope:
    description: "{String} Installation scope."
    required: false
    default: "CurrentUser"
  force:
    description: "{Boolean} Whether to force install or reinstall target (pre release) version."
    required: false
    default: "False"
  keepsetting:
    description: "{Boolean} Whether to keep the setting that modified by this action."
    required: false
    default: "True"
  toolkit_version:
    description: "{SemVer} Target version."
    required: false
    deprecationMessage: "Replaced by input `version`!"
  toolkit_allowprerelease:
    description: "{Boolean} Whether to allow target pre release version."
    required: false
    deprecationMessage: "Replaced by input `allowprerelease`!"
runs:
  using: "composite"
  steps:
    - name: "Throw Error - Input `sudo`"
      if: "${{inputs.sudo != 'False' && inputs.sudo != 'True'}}"
      run: |
        Write-Host -Object '::error::Input `sudo` is not a boolean!'
        Exit 1
      shell: "pwsh"
    - name: "Main (Non-Windows)"
      if: "${{runner.os != 'Windows' && inputs.sudo == 'False'}}"
      env:
        INPUT_ALLOWPRERELEASE: "${{inputs.toolkit_allowprerelease || inputs.allowprerelease}}"
        INPUT_FORCE: "${{inputs.force}}"
        INPUT_KEEPSETTING: "${{inputs.keepsetting}}"
        INPUT_SCOPE: "${{inputs.scope}}"
        INPUT_SUDO: "${{inputs.sudo}}"
        INPUT_VERSION: "${{inputs.toolkit_version || inputs.version}}"
      run: |
        pwsh -NonInteractive "$GITHUB_ACTION_PATH/main.ps1"
      shell: "sh"
    - name: "Main (Non-Windows, Sudo)"
      if: "${{runner.os != 'Windows' && inputs.sudo == 'True'}}"
      env:
        INPUT_ALLOWPRERELEASE: "${{inputs.toolkit_allowprerelease || inputs.allowprerelease}}"
        INPUT_FORCE: "${{inputs.force}}"
        INPUT_KEEPSETTING: "${{inputs.keepsetting}}"
        INPUT_SUDO: "${{inputs.sudo}}"
        INPUT_SCOPE: "${{inputs.scope}}"
        INPUT_VERSION: "${{inputs.toolkit_version || inputs.version}}"
      run: |
        sudo --non-interactive --preserve-env pwsh -NonInteractive "$GITHUB_ACTION_PATH/main.ps1"
      shell: "sh"
    - name: "Main (Windows)"
      if: "${{runner.os == 'Windows'}}"
      env:
        INPUT_ALLOWPRERELEASE: "${{inputs.toolkit_allowprerelease || inputs.allowprerelease}}"
        INPUT_FORCE: "${{inputs.force}}"
        INPUT_KEEPSETTING: "${{inputs.keepsetting}}"
        INPUT_SUDO: "${{inputs.sudo}}"
        INPUT_SCOPE: "${{inputs.scope}}"
        INPUT_VERSION: "${{inputs.toolkit_version || inputs.version}}"
      run: |
        pwsh -NonInteractive (Join-Path -Path $Env:GITHUB_ACTION_PATH -ChildPath 'main.ps1')
      shell: "pwsh"
branding:
  icon: "package"
  color: "blue"
