name: "Setup PowerShell Toolkit"
author: "hugoalh Studio"
description: "Setup PowerShell module `hugoalh.GitHubActionsToolkit`."
inputs:
  version:
    description: "{String} Target version."
    required: false
    default: "Latest"
  allowprerelease:
    description: "{Boolean} Whether to allow target pre release version."
    required: false
    default: "False"
runs:
  using: "composite"
  steps:
    - name: "Main (Non-Windows)"
      if: "${{runner.os != 'Windows'}}"
      env:
        INPUT_VERSION: "${{inputs.version}}"
        INPUT_ALLOWPRERELEASE: "${{inputs.allowprerelease}}"
      run: |
        sudo --non-interactive --preserve-env pwsh -NonInteractive "$GITHUB_ACTION_PATH/main.ps1"
      shell: "sh"
    - name: "Main (Windows)"
      if: "${{runner.os == 'Windows'}}"
      env:
        INPUT_VERSION: "${{inputs.version}}"
        INPUT_ALLOWPRERELEASE: "${{inputs.allowprerelease}}"
      run: |
        pwsh -NonInteractive (Join-Path -Path $Env:GITHUB_ACTION_PATH -ChildPath 'main.ps1')
      shell: "pwsh"
branding:
  icon: "package"
  color: "blue"
