# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Test"
on:
  workflow_dispatch:
jobs:
  main:
    name: "${{matrix.os}} (${{matrix.scope}})"
    runs-on: "${{matrix.os}}"
    strategy:
      matrix:
        os:
          - "macos-latest"
          - "ubuntu-latest"
          - "windows-latest"
        scope:
          - "AllUsers"
          - "CurrentUser"
      fail-fast: false
    steps:
      - name: "Setup PowerShell Toolkit"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@main"
        with:
          scope: "${{matrix.scope}}"
      - name: "Test Toolkit"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          Test-GitHubActionsEnvironment
          Write-GitHubActionsNotice -Message 'Hello, world!'
        shell: "pwsh"
