# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Test"
on:
  workflow_dispatch:
jobs:
  main:
    name: "${{matrix.os}}"
    permissions: {}
    runs-on: "${{matrix.os}}"
    strategy:
      matrix:
        os:
          - "macos-latest"
          - "ubuntu-latest"
          - "windows-latest"
      fail-fast: false
    steps:
      - name: "Setup CurrentUser"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@main"
      - name: "Test CurrentUser"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          Test-GitHubActionsEnvironment
          Write-GitHubActionsNotice -Message 'Hello, world!'
        shell: "pwsh"
      - name: "Setup AllUsers"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@main"
        with:
          sudo: "True"
          scope: "AllUsers"
          force: "True"
      - name: "Test AllUsers"
        run: |
          Import-Module -Name 'hugoalh.GitHubActionsToolkit' -Scope 'Local'
          Test-GitHubActionsEnvironment
          Write-GitHubActionsNotice -Message 'Hello, world!'
        shell: "pwsh"
      - name: "Setup Uninstall"
        uses: "hugoalh-studio/setup-powershell-toolkit-ghaction@main"
        with:
          sudo: "True"
          version: "False"
